// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAction = `-- name: CreateAction :one
INSERT INTO actions (workflow_id, type, position, config)
VALUES ($1, $2, $3, $4)
RETURNING id::text, workflow_id::text, type, position, config, created_at
`

type CreateActionParams struct {
	WorkflowID string `json:"workflow_id"`
	Type       string `json:"type"`
	Position   int32  `json:"position"`
	Config     []byte `json:"config"`
}

type CreateActionRow struct {
	ID         string             `json:"id"`
	WorkflowID string             `json:"workflow_id"`
	Type       string             `json:"type"`
	Position   int32              `json:"position"`
	Config     []byte             `json:"config"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAction(ctx context.Context, arg CreateActionParams) (CreateActionRow, error) {
	row := q.db.QueryRow(ctx, createAction,
		arg.WorkflowID,
		arg.Type,
		arg.Position,
		arg.Config,
	)
	var i CreateActionRow
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Type,
		&i.Position,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAction = `-- name: DeleteAction :exec
DELETE FROM actions WHERE id = $1 AND workflow_id = $2
`

type DeleteActionParams struct {
	ID         string `json:"id"`
	WorkflowID string `json:"workflow_id"`
}

func (q *Queries) DeleteAction(ctx context.Context, arg DeleteActionParams) error {
	_, err := q.db.Exec(ctx, deleteAction, arg.ID, arg.WorkflowID)
	return err
}

const deleteActionsByWorkflow = `-- name: DeleteActionsByWorkflow :exec
DELETE FROM actions WHERE workflow_id = $1
`

func (q *Queries) DeleteActionsByWorkflow(ctx context.Context, workflowID string) error {
	_, err := q.db.Exec(ctx, deleteActionsByWorkflow, workflowID)
	return err
}

const getAction = `-- name: GetAction :one
SELECT id::text, workflow_id::text, type, position, config, created_at
FROM actions
WHERE id = $1 AND workflow_id = $2
`

type GetActionParams struct {
	ID         string `json:"id"`
	WorkflowID string `json:"workflow_id"`
}

type GetActionRow struct {
	ID         string             `json:"id"`
	WorkflowID string             `json:"workflow_id"`
	Type       string             `json:"type"`
	Position   int32              `json:"position"`
	Config     []byte             `json:"config"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAction(ctx context.Context, arg GetActionParams) (GetActionRow, error) {
	row := q.db.QueryRow(ctx, getAction, arg.ID, arg.WorkflowID)
	var i GetActionRow
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Type,
		&i.Position,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const listActionsByWorkflow = `-- name: ListActionsByWorkflow :many
SELECT id::text, workflow_id::text, type, position, config, created_at
FROM actions
WHERE workflow_id = $1
ORDER BY position
`

type ListActionsByWorkflowRow struct {
	ID         string             `json:"id"`
	WorkflowID string             `json:"workflow_id"`
	Type       string             `json:"type"`
	Position   int32              `json:"position"`
	Config     []byte             `json:"config"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListActionsByWorkflow(ctx context.Context, workflowID string) ([]ListActionsByWorkflowRow, error) {
	rows, err := q.db.Query(ctx, listActionsByWorkflow, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActionsByWorkflowRow
	for rows.Next() {
		var i ListActionsByWorkflowRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.Type,
			&i.Position,
			&i.Config,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAction = `-- name: UpdateAction :one
UPDATE actions
SET type = $2, position = $3, config = $4
WHERE id = $1 AND workflow_id = $5
RETURNING id::text, workflow_id::text, type, position, config, created_at
`

type UpdateActionParams struct {
	ID         string `json:"id"`
	Type       string `json:"type"`
	Position   int32  `json:"position"`
	Config     []byte `json:"config"`
	WorkflowID string `json:"workflow_id"`
}

type UpdateActionRow struct {
	ID         string             `json:"id"`
	WorkflowID string             `json:"workflow_id"`
	Type       string             `json:"type"`
	Position   int32              `json:"position"`
	Config     []byte             `json:"config"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateAction(ctx context.Context, arg UpdateActionParams) (UpdateActionRow, error) {
	row := q.db.QueryRow(ctx, updateAction,
		arg.ID,
		arg.Type,
		arg.Position,
		arg.Config,
		arg.WorkflowID,
	)
	var i UpdateActionRow
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Type,
		&i.Position,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}
