// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, name, hashed_key)
VALUES ($1, $2, $3)
RETURNING id::text, user_id::text, name, hashed_key, created_at
`

type CreateAPIKeyParams struct {
	UserID    string `json:"user_id"`
	Name      string `json:"name"`
	HashedKey string `json:"hashed_key"`
}

type CreateAPIKeyRow struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Name      string             `json:"name"`
	HashedKey string             `json:"hashed_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey, arg.UserID, arg.Name, arg.HashedKey)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.HashedKey,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = $1
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, id)
	return err
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id::text, user_id::text, name, hashed_key, created_at
FROM api_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListAPIKeysByUserRow struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Name      string             `json:"name"`
	HashedKey string             `json:"hashed_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID string) ([]ListAPIKeysByUserRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysByUserRow
	for rows.Next() {
		var i ListAPIKeysByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.HashedKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
