// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Action struct {
	ID         string             `json:"id"`
	WorkflowID string             `json:"workflow_id"`
	Type       string             `json:"type"`
	Position   int32              `json:"position"`
	Config     []byte             `json:"config"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ApiKey struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Name      string             `json:"name"`
	HashedKey string             `json:"hashed_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Trigger struct {
	ID         string             `json:"id"`
	WorkflowID string             `json:"workflow_id"`
	Type       string             `json:"type"`
	Config     []byte             `json:"config"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           string             `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Workflow struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Name      string             `json:"name"`
	IsEnabled bool               `json:"is_enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type WorkflowRun struct {
	ID          string             `json:"id"`
	WorkflowID  string             `json:"workflow_id"`
	Status      string             `json:"status"`
	TriggerType string             `json:"trigger_type"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type WorkflowRunLog struct {
	ID             string             `json:"id"`
	RunID          string             `json:"run_id"`
	ActionID       string             `json:"action_id"`
	ActionPosition int32              `json:"action_position"`
	Success        bool               `json:"success"`
	Message        string             `json:"message"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
