// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (user_id, name)
VALUES ($1, $2)
RETURNING id::text, user_id::text, name, is_enabled, created_at, updated_at
`

type CreateWorkflowParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

type CreateWorkflowRow struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Name      string             `json:"name"`
	IsEnabled bool               `json:"is_enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (CreateWorkflowRow, error) {
	row := q.db.QueryRow(ctx, createWorkflow, arg.UserID, arg.Name)
	var i CreateWorkflowRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkflow = `-- name: DeleteWorkflow :one
DELETE FROM workflows
WHERE id = $1 AND user_id = $2
RETURNING id::text
`

type DeleteWorkflowParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteWorkflow(ctx context.Context, arg DeleteWorkflowParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteWorkflow, arg.ID, arg.UserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id::text, user_id::text, name, is_enabled, created_at, updated_at
FROM workflows
WHERE id = $1 AND user_id = $2
`

type GetWorkflowParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type GetWorkflowRow struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Name      string             `json:"name"`
	IsEnabled bool               `json:"is_enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWorkflow(ctx context.Context, arg GetWorkflowParams) (GetWorkflowRow, error) {
	row := q.db.QueryRow(ctx, getWorkflow, arg.ID, arg.UserID)
	var i GetWorkflowRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkflowsByUser = `-- name: ListWorkflowsByUser :many
SELECT id::text, user_id::text, name, is_enabled, created_at, updated_at
FROM workflows
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListWorkflowsByUserRow struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Name      string             `json:"name"`
	IsEnabled bool               `json:"is_enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListWorkflowsByUser(ctx context.Context, userID string) ([]ListWorkflowsByUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowsByUserRow
	for rows.Next() {
		var i ListWorkflowsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflow = `-- name: UpdateWorkflow :one
UPDATE workflows
SET name = $2, is_enabled = $3, updated_at = now()
WHERE id = $1 AND user_id = $4
RETURNING id::text, user_id::text, name, is_enabled, created_at, updated_at
`

type UpdateWorkflowParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	IsEnabled bool   `json:"is_enabled"`
	UserID    string `json:"user_id"`
}

type UpdateWorkflowRow struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Name      string             `json:"name"`
	IsEnabled bool               `json:"is_enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (UpdateWorkflowRow, error) {
	row := q.db.QueryRow(ctx, updateWorkflow,
		arg.ID,
		arg.Name,
		arg.IsEnabled,
		arg.UserID,
	)
	var i UpdateWorkflowRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
