// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_run_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertWorkflowRunLog = `-- name: InsertWorkflowRunLog :one
INSERT INTO workflow_run_logs (run_id, action_id, action_position, success, message)
VALUES ($1, $2, $3, $4, $5)
RETURNING id::text, run_id::text, action_id::text, action_position, success, message, created_at
`

type InsertWorkflowRunLogParams struct {
	RunID          string `json:"run_id"`
	ActionID       string `json:"action_id"`
	ActionPosition int32  `json:"action_position"`
	Success        bool   `json:"success"`
	Message        string `json:"message"`
}

type InsertWorkflowRunLogRow struct {
	ID             string             `json:"id"`
	RunID          string             `json:"run_id"`
	ActionID       string             `json:"action_id"`
	ActionPosition int32              `json:"action_position"`
	Success        bool               `json:"success"`
	Message        string             `json:"message"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertWorkflowRunLog(ctx context.Context, arg InsertWorkflowRunLogParams) (InsertWorkflowRunLogRow, error) {
	row := q.db.QueryRow(ctx, insertWorkflowRunLog,
		arg.RunID,
		arg.ActionID,
		arg.ActionPosition,
		arg.Success,
		arg.Message,
	)
	var i InsertWorkflowRunLogRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ActionID,
		&i.ActionPosition,
		&i.Success,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkflowRunLogs = `-- name: ListWorkflowRunLogs :many
SELECT id::text, run_id::text, action_id::text, action_position, success, message, created_at
FROM workflow_run_logs
WHERE run_id = $1
ORDER BY action_position
`

type ListWorkflowRunLogsRow struct {
	ID             string             `json:"id"`
	RunID          string             `json:"run_id"`
	ActionID       string             `json:"action_id"`
	ActionPosition int32              `json:"action_position"`
	Success        bool               `json:"success"`
	Message        string             `json:"message"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListWorkflowRunLogs(ctx context.Context, runID string) ([]ListWorkflowRunLogsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowRunLogs, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowRunLogsRow
	for rows.Next() {
		var i ListWorkflowRunLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ActionID,
			&i.ActionPosition,
			&i.Success,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
